# settings.conf
# General user settings for Arch Smart Update.
# This file will NEVER be overwritten by the script during updates.

# Set to true to always ask if you want to refresh mirrors before syncing databases.
PROMPT_MIRROR_REFRESH=false
